-- Table: insert accounts type

INSERT INTO accounts_type(code, name, createdat, updatedat)VALUES ('CC', 'CONTA_CORRENTE', current_date, current_date);
INSERT INTO accounts_type(code, name, createdat, updatedat)VALUES ('CP', 'CONTA_POUPANCA', current_date, current_date);
INSERT INTO accounts_type(code, name, createdat, updatedat)VALUES ('CF', 'CONTA_FACIL', current_date, current_date);


-- Table: insert banks
INSERT INTO banks(code, name, urlimg, createdat, updatedat)VALUES ('001','Banco do Brasil', 'https://transfeera.com/wp-content/uploads/2020/02/transfeera-banco-brasil.svg', current_date, current_date);
INSERT INTO banks(code, name, urlimg, createdat, updatedat)VALUES ('104','Caixa', 'https://transfeera.com/wp-content/uploads/2020/02/transfeera-banco-caixa.svg', current_date, current_date);
INSERT INTO banks(code, name, urlimg, createdat, updatedat)VALUES ('237','Bradesco', 'https://transfeera.com/wp-content/uploads/2020/02/transfeera-banco-bradesco.svg', current_date, current_date);
INSERT INTO banks(code, name, urlimg, createdat, updatedat)VALUES ('756','Sicoob', 'https://transfeera.com/wp-content/uploads/2020/02/transfeera-banco-sicoob.svg', current_date, current_date);
INSERT INTO banks(code, name, urlimg, createdat, updatedat)VALUES ('341','Itaú', 'https://transfeera.com/wp-content/uploads/2020/02/transfeera-banco-itau.svg', current_date, current_date);


-- Table: insert favorites

INSERT INTO favorites(name, nif, email, agency, agencydigit, account, accountdigit,  bankcode, accounttypecode, status, createdat, updatedat)VALUES ('Dean Winchester', '72385156016', 'dean@gmail.com', '0814', '0', '0092847', '9', '237', 'CC', 'R', current_date, current_date);
INSERT INTO favorites(name, nif, email, agency, agencydigit, account, accountdigit,  bankcode, accounttypecode, status, createdat, updatedat)VALUES ('Sam Winchester', '96104562000', 'dean@gmail.com', '0814', '0', '0092847', '9', '237', 'CC', 'R', current_date, current_date);
INSERT INTO favorites(name, nif, email, agency, agencydigit, account, accountdigit,  bankcode, accounttypecode, status, createdat, updatedat)VALUES ('John Wick', '98756157061', 'dean@gmail.com', '0814', '0', '0092847', '9', '237', 'CC', 'R', current_date, current_date);
INSERT INTO favorites(name, nif, email, agency, agencydigit, account, accountdigit,  bankcode, accounttypecode, status, createdat, updatedat)VALUES ('Darth Vader', '11050517067', 'dean@gmail.com', '0814', '0', '0092847', '9', '237', 'CC', 'V', current_date, current_date);
INSERT INTO favorites(name, nif, email, agency, agencydigit, account, accountdigit,  bankcode, accounttypecode, status, createdat, updatedat)VALUES ('John McClane', '85091680080', 'dean@gmail.com', '0814', '0', '0092847', '9', '237', 'CC', 'V', current_date, current_date);
INSERT INTO favorites(name, nif, email, agency, agencydigit, account, accountdigit,  bankcode, accounttypecode, status, createdat, updatedat)VALUES ('James Bond', '52236176066', 'dean@gmail.com', '0814', '0', '0092847', '9', '237', 'CC', 'V', current_date, current_date);
INSERT INTO favorites(name, nif, email, agency, agencydigit, account, accountdigit,  bankcode, accounttypecode, status, createdat, updatedat)VALUES ('Michael Corleone', '58232027096', 'dean@gmail.com', '0814', '0', '0092847', '9', '237', 'CC', 'V', current_date, current_date);
INSERT INTO favorites(name, nif, email, agency, agencydigit, account, accountdigit,  bankcode, accounttypecode, status, createdat, updatedat)VALUES ('Tony Stark', '36849064096', 'dean@gmail.com', '0814', '0', '0092847', '9', '237', 'CC', 'V', current_date, current_date);
INSERT INTO favorites(name, nif, email, agency, agencydigit, account, accountdigit,  bankcode, accounttypecode, status, createdat, updatedat)VALUES ('Jack Sparrow', '30501613021', 'dean@gmail.com', '0814', '0', '0092847', '9', '237', 'CC', 'R', current_date, current_date);
INSERT INTO favorites(name, nif, email, agency, agencydigit, account, accountdigit,  bankcode, accounttypecode, status, createdat, updatedat)VALUES ('Hannibal Lecter', '49893995019', 'dean@gmail.com', '0814', '0', '0092847', '9', '237', 'CC', 'R', current_date, current_date);
INSERT INTO favorites(name, nif, email, agency, agencydigit, account, accountdigit,  bankcode, accounttypecode, status, createdat, updatedat)VALUES ('Forrest Gump', '89068189042', 'dean@gmail.com', '0814', '0', '0092847', '9', '237', 'CC', 'R', current_date, current_date);
INSERT INTO favorites(name, nif, email, agency, agencydigit, account, accountdigit,  bankcode, accounttypecode, status, createdat, updatedat)VALUES ('Rocky Balboa', '99706243003', 'dean@gmail.com', '0814', '0', '0092847', '9', '237', 'CC', 'R', current_date, current_date);
INSERT INTO favorites(name, nif, email, agency, agencydigit, account, accountdigit,  bankcode, accounttypecode, status, createdat, updatedat)VALUES ('Yoda', '87510830001', 'dean@gmail.com', '0814', '0', '0092847', '9', '237', 'CC', 'V', current_date, current_date);
INSERT INTO favorites(name, nif, email, agency, agencydigit, account, accountdigit,  bankcode, accounttypecode, status, createdat, updatedat)VALUES ('Marvel Corporation S/A', '35525380030', 'dean@gmail.com', '0814', '0', '0092847', '9', '237', 'CC', 'R', current_date, current_date);
INSERT INTO favorites(name, nif, email, agency, agencydigit, account, accountdigit,  bankcode, accounttypecode, status, createdat, updatedat)VALUES ('Avengers Corporation S/A', '56202172053', 'dean@gmail.com', '0814', '0', '0092847', '9', '237', 'CC', 'R', current_date, current_date);
INSERT INTO favorites(name, nif, email, agency, agencydigit, account, accountdigit,  bankcode, accounttypecode, status, createdat, updatedat)VALUES ('Skynet S/A', '29933084089', 'dean@gmail.com', '0814', '0', '0092847', '9', '237', 'CC', 'V', current_date, current_date);
INSERT INTO favorites(name, nif, email, agency, agencydigit, account, accountdigit,  bankcode, accounttypecode, status, createdat, updatedat)VALUES ('DC Comics', '45265592024', 'dean@gmail.com', '0814', '0', '0092847', '9', '237', 'CC', 'R', current_date, current_date);
INSERT INTO favorites(name, nif, email, agency, agencydigit, account, accountdigit,  bankcode, accounttypecode, status, createdat, updatedat)VALUES ('Optimus Prime', '88325233028', 'dean@gmail.com', '0814', '0', '0092847', '9', '237', 'CC', 'R', current_date, current_date);
INSERT INTO favorites(name, nif, email, agency, agencydigit, account, accountdigit,  bankcode, accounttypecode, status, createdat, updatedat)VALUES ('Sheldon Cooper', '96849319051', 'dean@gmail.com', '0814', '0', '0092847', '9', '237', 'CC', 'R', current_date, current_date);
INSERT INTO favorites(name, nif, email, agency, agencydigit, account, accountdigit,  bankcode, accounttypecode, status, createdat, updatedat)VALUES ('Sherlock Holmes', '08985256084', 'dean@gmail.com', '0814', '0', '0092847', '9', '237', 'CC', 'R', current_date, current_date);
INSERT INTO favorites(name, nif, email, agency, agencydigit, account, accountdigit,  bankcode, accounttypecode, status, createdat, updatedat)VALUES ('Will Smith', '24957553050', 'dean@gmail.com', '0814', '0', '0092847', '9', '237', 'CC', 'R', current_date, current_date);
INSERT INTO favorites(name, nif, email, agency, agencydigit, account, accountdigit,  bankcode, accounttypecode, status, createdat, updatedat)VALUES ('Harry Potter', '04850124054', 'dean@gmail.com', '0814', '0', '0092847', '9', '237', 'CC', 'R', current_date, current_date);
INSERT INTO favorites(name, nif, email, agency, agencydigit, account, accountdigit,  bankcode, accounttypecode, status, createdat, updatedat)VALUES ('Ethan Hunt', '77280675085', 'dean@gmail.com', '0814', '0', '0092847', '9', '237', 'CC', 'R', current_date, current_date);
INSERT INTO favorites(name, nif, email, agency, agencydigit, account, accountdigit,  bankcode, accounttypecode, status, createdat, updatedat)VALUES ('Sarah Connor', '14605344098', 'dean@gmail.com', '0814', '0', '0092847', '9', '237', 'CC', 'R', current_date, current_date);